# Generated by Django 2.0.9 on 2018-10-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('mac', models.TextField()),
                ('site', models.TextField()),
                ('source', models.TextField()),
                ('destination', models.TextField()),
                ('device', models.TextField()),
                ('download', models.TextField()),
                ('upload', models.TextField()),
            ],
        ),
    ]
