# Generated by Django 2.0.9 on 2018-10-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportmaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Macname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.TextField()),
                ('nickname', models.TextField()),
            ],
        ),
    ]
