# Generated by Django 2.0.9 on 2018-10-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportmaker', '0002_macname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macname',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
