# Generated by Django 2.0.9 on 2018-10-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportmaker', '0003_auto_20181025_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macname',
            name='mac',
            field=models.TextField(unique=True),
        ),
    ]
